# print("\"prakash\"")
# print("\'prakash\'")
# print("\\\\")
# print("'this is single intended comma'")
# print("line A \nline B")
# print("\"there are mountning /\\/\\/\\/\\\"")
# print("\'\"\\\\")
# print("pra\bkash\b")
# print("prakash\tkC")
# print("\\\' \\\\\"")
# print("this\r is character")
# print("this is lineA\vline B")
# print("thisis lineA\nLine B")
# print("this is linea\vline B")
# print("this\r is line A\n Line B")
# print("this\r is sequ\vence")
# print(r"this is \\ sequence")
# print("\'\"\\\\")
# print("\"this is escape formate\",\'/\\/\\/\\")

