# num1=int(input("Enter First Number: "))
# num2=int(input("Enter Second Number: "))
# num3=int(input("Enter third Number: "))
# print("Total three number", num1+num2+num3)
# num1=int(input("Enter First Number: "))
# num2=int(input("Enter Second Number: "))
# num3=int(input("Enter third Number: "))
# print("Multiply three number", num1*num2*num3)

# name=input("enter a name: ")
# address=input("enter a address: ")
# age=input("enter a age: a")
# print(f"my name is {name}. my address is {address}. my agr is {age}.")
# num1=int(input("Enter first nmeber "))
# num2=int(input("Enter second nmuber "))
# print(num1+num2)